[package]
name = "audio-stream-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
audio-stream-audio-common = { path = "../crates/audio-common" }
audio-stream-protocol = { path = "../crates/protocol" }
audio-stream-transport = { path = "../crates/transport" }
bytes.workspace = true
clap.workspace = true
crossbeam-channel.workspace = true
quinn.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
qrcodegen.workspace = true
wasapi = "0.16.0"
windows.workspace = true
